basic_settings:
  site_title: Cédric Colas
  site_tagline: ''
  favicon_image: /images/favicon.png
  site_description: 'Website of Cédric Colas'
  default_featured_image: '/images/logo.png'

header_settings:
  logo_image: /images/logo.png
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'About me'
      url: '/'
    - title: 'Fun projects'
      url: '/project/'
    - title: 'Tangible Dreams'
      url: '/blog/'
    - title: 'Photography'
      url: '/photographs'
    - title: 'Publications'
      url: '/publications'
    - title: 'Contact'
      url: '/contact'


grid_settings:
  overlay_opacity: 0.7
  grid_spacing: 20

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: 'https://twitter.com/cedcolas'
  instagram_url: 'https://www.instagram.com/bkayf_'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  gscholar_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: 'https://github.com/ccolas'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: 'https://open.spotify.com/user/bkayf?si=d20c664357934f21'
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#010138'              # Deep oceanic blue-black
  background_alt_color: '#010138'          # Dark teal-navy shade
  text_dark_color: '#e0e0ffff'               # Slightly cool white
  text_medium_color: '#e0e0ffff'             # Pale steel-gray
  text_light_color: '#e0e0ffff'              # Muted blue-gray
  accent_color: '#fe4791'                  # Neon pink (unchanged)
  link_color: '#535de6'                    # Bright electric blue
  link_hover_color: '#60A5FA'              # Softer sky-blue on hover
  border_color: '#1E3542'                  # Dark marine-blue border
  overlay_background_color: '#050345'   # Semi-transparent deep oceanic
  overlay_text_color: '#E6F0F8'            # Cool white
  overlay_accent_color: '#FF3CAC'          # Neon pink accent
  error_color: '#FF5F6D'                   # Vivid coral-red


font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">'
  title_font: '"Inter", sans-serif'
  body_font: '"Inter", sans-serif'
  regular_weight: 100
  bold_weight: 900
  site_title:
    small_size: 20
    medium_size: 30
    large_size: 40
    weight: 500
    letter_spacing: -0.02
  site_tagline:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 300
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 30
    medium_size: 15
    large_size: 16
    weight: 500
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 26
    large_size: 30
    weight: 500
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 15
    medium_size: 16
    large_size: 17
    weight: 300
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 500
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 500
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 500
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 13
    medium_size: 14
    large_size: 17
    weight: 300
    bold_weight: 900
    letter_spacing: 0
    line_height: 1.5
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 500
    letter_spacing: 0

advanced_settings:
  ajax_loading: false
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""